#!/bin/zsh

local ppid
ppid=$(ps ax -eo pid,ppid,comm,args --sort=-%cpu | fzf --ansi --header="Select a process to kill the parent" | awk '{print $2}')

# Exit early if no selection
if [[ -z "$ppid" ]]; then
  echo "No process selected."
  return 0
fi

echo "Kill PID $ppid with (1) normal kill or (2) force kill?"
read -r choice
if [[ "$choice" == "2" ]]; then
  kill -9 "$ppid"
else
  kill "$ppid"
fi
